// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShameTheThronesV2.DB;
using System;

namespace ShameTheThronesV2.Migrations
{
    [DbContext(typeof(ShameTheThronesContext))]
    partial class ShameTheThronesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShameTheThronesV2.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CommentID");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("RatingID");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("CommentID");

                    b.HasIndex("RatingID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ShameTheThronesV2.Models.Rating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("RestroomID");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<double>("Value");

                    b.HasKey("ID");

                    b.HasIndex("RestroomID");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("ShameTheThronesV2.Models.Restroom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Description");

                    b.Property<byte?>("Gender");

                    b.Property<decimal>("Lat");

                    b.Property<decimal>("Lng");

                    b.Property<string>("State");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.Property<int?>("ZipCode");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Restrooms");
                });

            modelBuilder.Entity("ShameTheThronesV2.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShameTheThronesV2.Models.Comment", b =>
                {
                    b.HasOne("ShameTheThronesV2.Models.Comment")
                        .WithMany("Replies")
                        .HasForeignKey("CommentID");

                    b.HasOne("ShameTheThronesV2.Models.Rating")
                        .WithMany("Comments")
                        .HasForeignKey("RatingID");

                    b.HasOne("ShameTheThronesV2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("ShameTheThronesV2.Models.Rating", b =>
                {
                    b.HasOne("ShameTheThronesV2.Models.Restroom")
                        .WithMany("Ratings")
                        .HasForeignKey("RestroomID");
                });

            modelBuilder.Entity("ShameTheThronesV2.Models.Restroom", b =>
                {
                    b.HasOne("ShameTheThronesV2.Models.User", "User")
                        .WithMany("Restrooms")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
